#!/usr/bin/env node
// Materialize the Notion newsletter entries as a relative TypeScript module.
//
// Kudzu 0.8.x rejects every package (non-relative) import that is referenced
// outside a JSX event handler — see the `packageImportBindings` guard in
// @kudzujs/core/framework/build.mjs. Up to 0.5.x the pages could call
// `fetchNewsEntries()` from `@otw/notion-content` directly at build time;
// they no longer can. Kudzu does compile relative TypeScript modules reachable
// from a page and folds JSON-safe immutable arrays into static output, so the
// fetch moves here and the pages import the generated module instead.
//
// Runs as part of `pnpm --filter @otw/web-kudzu build`, so the Notion work
// stays inside the measured build (scripts/build-stats.mjs) exactly like it
// does for every other variant. `fetchNewsEntries()` is memoized per
// auth+databaseId, and `pnpm run prefetch:content` primes the same cache the
// other variants read.
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { fetchNewsEntries } from "@otw/notion-content";

const appDir = join(dirname(fileURLToPath(import.meta.url)), "..");
const outFile = join(appDir, "src", "generated", "entries.ts");

const entries = await fetchNewsEntries();

// Only the fields the pages actually render. `headings` is unused here and
// carrying it would inflate every compiled page's build-time module.
const payload = entries.map(entry => ({
  id: entry.id,
  title: entry.title,
  date: entry.date,
  coverUrl: entry.coverUrl,
  html: entry.html
}));

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(
  outFile,
  `// GENERATED by scripts/gen-content.mjs — do not edit, do not commit.
export interface NewsEntry {
  id: string;
  title: string;
  date: string | null;
  coverUrl: string | null;
  html: string;
}

const entries: NewsEntry[] = ${JSON.stringify(payload)};

export default entries;
`
);

console.log(`gen-content: wrote ${payload.length} entr${payload.length === 1 ? "y" : "ies"} to src/generated/entries.ts`);
