#!/usr/bin/env node
// Materialize the shared @otw/docs-data corpus as Docusaurus content:
//
//   docs/<section>/_category_.json   -- sidebar label + position, one per
//                                        @otw/docs-data SECTIONS entry
//   docs/<section>/<slug>.md         -- one per DocPage, front matter
//                                        carries `slug` (forces the final
//                                        URL) and `sidebar_position`
//                                        (forces sidebar/prev-next order)
//   src/generated/nav.json           -- {handle,title,description,firstSlug}
//                                        per section, consumed by
//                                        src/pages/index.js for the home
//                                        page's section cards
//
// This keeps docusaurus.config.js on the standard `@docusaurus/preset-classic`
// docs plugin (see that file's header comment for why: it avoids README.md
// defect #4, the custom-plugin addRoute/baseUrl hydration bug) instead of a
// bespoke content plugin — the assignment's recommended shape for this
// variant ("커스텀 플러그인보다 표준 docs 플러그인 + 생성된 md 파일 사용 권장").
//
// Corpus size comes from OTW_DOCS_SIZE (default 120, see
// @otw/docs-data#resolveDocsSize) so the docs-scaling bench track can sweep
// it without touching source. docs/ is wiped and rewritten from scratch on
// every run so a smaller OTW_DOCS_SIZE never leaves orphan pages behind
// from a previous, larger run.
import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { getDocs, resolveDocsSize, SECTIONS } from "@otw/docs-data";

const appDir = join(dirname(fileURLToPath(import.meta.url)), "..");
const docsDir = join(appDir, "docs");
const generatedDir = join(appDir, "src", "generated");

const corpus = getDocs(resolveDocsSize(process.env.OTW_DOCS_SIZE));

rmSync(docsDir, { recursive: true, force: true });
mkdirSync(docsDir, { recursive: true });
mkdirSync(generatedDir, { recursive: true });

// Every front-matter value below is our own generated text (no external
// input), but quote defensively so a stray `:` or `#` in a title/description
// can never be misread as YAML syntax.
const yamlString = value => `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;

// One `_category_.json` per section, `position` matching SECTIONS order —
// without it the autogenerated sidebar would fall back to alphabetical
// folder order (data, deploy, reference, rendering, routing, start), which
// does not match the corpus's section order.
SECTIONS.forEach((section, sectionIndex) => {
  mkdirSync(join(docsDir, section.handle), { recursive: true });
  writeFileSync(
    join(docsDir, section.handle, "_category_.json"),
    `${JSON.stringify({ label: section.title, position: sectionIndex + 1 }, null, 2)}\n`
  );
});

const pagesBySection = new Map(SECTIONS.map(section => [section.handle, []]));
for (const page of corpus.pages) pagesBySection.get(page.section).push(page);

for (const pages of pagesBySection.values()) {
  pages.forEach((page, indexInSection) => {
    const frontMatter = [
      "---",
      `title: ${yamlString(page.title)}`,
      `description: ${yamlString(page.description)}`,
      // Absolute slug (appended to the docs plugin's routeBasePath,
      // "guide") — forces `/guide/<section>/<slug>/` regardless of file
      // layout, per the assignment's "slug front matter로 강제" requirement.
      `slug: /${page.section}/${page.slug}`,
      // Within-section order, matching DocPage.order's relative order for
      // this section — the sidebar (and, transitively, prev/next
      // pagination — see src/theme/DocItem/Paginator) flattens
      // depth-first through the section categories in `_category_.json`
      // position order, so this reproduces the corpus's global reading
      // order exactly.
      `sidebar_position: ${indexInSection + 1}`,
      "---",
      ""
    ].join("\n");
    writeFileSync(join(docsDir, page.section, `${page.slug}.md`), `${frontMatter}\n${page.body}\n`);
  });
}

const nav = corpus.sections
  .map(section => {
    const first = pagesBySection.get(section.handle)[0];
    return first
      ? { handle: section.handle, title: section.title, description: section.description, firstSlug: first.slug }
      : null;
  })
  .filter(section => section !== null);

writeFileSync(join(generatedDir, "nav.json"), `${JSON.stringify(nav, null, 2)}\n`);

console.log(`gen-docs: ${corpus.pages.length} pages across ${SECTIONS.length} sections`);
