#!/usr/bin/env node
// Materialize the Vine docs corpus (@otw/docs-data) as a relative
// TypeScript module.
//
// Kudzu 0.8.x rejects every package (non-relative) import that is
// referenced outside a JSX event handler — see the `packageImportBindings`
// guard in @kudzujs/core/framework/build.mjs. Pages therefore cannot call
// `getDocs()` from "@otw/docs-data" directly; the generator runs here
// instead and pages import the generated module, which Kudzu does compile
// and whose JSON-safe immutable arrays it folds into static output. Same
// pattern as apps/shop-kudzu/scripts/gen-catalog.mjs.
//
// Markdown bodies are also rendered to HTML at this stage, not at request
// time, since Kudzu pages have no server to defer the work to. The corpus
// only ever mixes three block shapes (see packages/docs-data/src/index.ts
// pageFor()): "## heading" lines, "```" fenced code, and plain paragraphs,
// separated by blank lines — so the converter below needs no markdown
// dependency, just those three rules.
//
// Corpus size comes from OTW_DOCS_SIZE (default 120), so the read/search
// scaling track can sweep it without touching source.
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { getDocs, resolveDocsSize } from "@otw/docs-data";

const appDir = join(dirname(fileURLToPath(import.meta.url)), "..");
const corpus = getDocs(resolveDocsSize(process.env.OTW_DOCS_SIZE));

const ESCAPES = { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" };
function escapeHtml(text) {
  return text.replace(/[&<>"']/g, character => ESCAPES[character]);
}

// Heading ids come from `page.headings`, in document order, rather than
// re-deriving a slug from the heading text — that list is already
// authoritative and the block order below matches it exactly (pageFor()
// pushes one "## heading" block per headings entry, in the same order).
function renderBody(page) {
  const blocks = page.body.split("\n\n");
  let headingIndex = 0;
  const html = [];
  for (const block of blocks) {
    if (block.startsWith("## ")) {
      const heading = page.headings[headingIndex];
      headingIndex += 1;
      html.push(`<h2 id="${heading.id}">${escapeHtml(heading.text)}</h2>`);
    } else if (block.startsWith("```")) {
      const lines = block.split("\n");
      const lang = lines[0].slice(3).trim();
      const code = lines.slice(1, -1).join("\n");
      html.push(`<pre><code class="language-${lang}">${escapeHtml(code)}</code></pre>`);
    } else {
      html.push(`<p>${escapeHtml(block)}</p>`);
    }
  }
  return html.join("\n");
}

// Only the fields pages actually render. `headings` itself is dropped —
// it is fully folded into `bodyHtml`'s <h2 id> anchors above, and carrying
// it too would inflate every compiled route's build-time module for no
// reason.
const pages = corpus.pages.map(page => ({
  slug: page.slug,
  section: page.section,
  title: page.title,
  description: page.description,
  order: page.order,
  bodyHtml: renderBody(page)
}));

const outDir = join(appDir, "src", "generated");
mkdirSync(outDir, { recursive: true });
writeFileSync(
  join(outDir, "docs.ts"),
  `// GENERATED by scripts/gen-docs.mjs — do not edit, do not commit.
export interface DocSection {
  handle: string;
  title: string;
  description: string;
}

export interface DocPageEntry {
  slug: string;
  section: string;
  title: string;
  description: string;
  order: number;
  bodyHtml: string;
}

export const sections: DocSection[] = ${JSON.stringify(corpus.sections)};

export const pages: DocPageEntry[] = ${JSON.stringify(pages)};
`
);

console.log(`gen-docs: wrote ${pages.length} page(s) across ${corpus.sections.length} section(s) to src/generated/docs.ts`);
